# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a8419aa4580b56e5eb3653e5002c7485e687b5d0ec7ea5ea060e314bdab18e26d9a5d98fcfbd315e054f11eab97acbf61eb507f7c73e23cc4fba421436782db

test:
  secret_key_base: c374e8631a2df3dc7dc5369de8bced5be843093ba52957c6d8f3a890aaffed7394842ed2878284378197e628eb8b53da9565c0dc0e4767f561d77bdeb2cb2e51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
